# Generated by Django 5.0.7 on 2024-08-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maestro", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quiebre",
            unique_together=set(),
        ),
    ]
