# Generated by Django 5.0.7 on 2024-08-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maestro", "0002_alter_quiebre_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quiebre",
            unique_together={("institucion", "medicamento")},
        ),
    ]
